services:
  app:
    container_name: auth-service
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    mem_limit: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - auth-network

  postgres:
    image: postgres:16
    container_name: auth-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 1G
    healthcheck:
      test: pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-authdb}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - auth-network

volumes:
  postgres_data:
    name: auth-postgres-data

networks:
  auth-network:
    name: auth-network
    driver: bridge
